def trans(text)
  text\
  .gsub(/ΰ/,"a")\
  .gsub(/ΐ/,"A")\
  .gsub(/α/,"b")\
  .gsub(/Α/,"B")\
  .gsub(/β/,"w")\
  .gsub(/Β/,"W")\
  .gsub(/γ/,"g")\
  .gsub(/Γ/,"G")\
  .gsub(/δ/,"d")\
  .gsub(/Δ/,"D")\
  .gsub(/ε/,"e")\
  .gsub(/Ε/,"E")\
  .gsub(/Έ/,"jo")\
  .gsub(/¨/,"Jo")\
  .gsub(/ζ/,"j")\
  .gsub(/Ζ/,"J")\
  .gsub(/η/,"z")\
  .gsub(/Η/,"Z")\
  .gsub(/θ/,"i")\
  .gsub(/Θ/,"I")\
  .gsub(/ι/,"i")\
  .gsub(/Ι/,"I")\
  .gsub(/κ/,"k")\
  .gsub(/Κ/,"K")\
  .gsub(/λ/,"l")\
  .gsub(/Λ/,"L")\
  .gsub(/μ/,"m")\
  .gsub(/Μ/,"M")\
  .gsub(/ν/,"n")\
  .gsub(/Ν/,"N")\
  .gsub(/ξ/,"o")\
  .gsub(/Ξ/,"O")\
  .gsub(/ο/,"p")\
  .gsub(/Ο/,"P")\
  .gsub(/π/,"r")\
  .gsub(/Π/,"R")\
  .gsub(/ρ/,"s")\
  .gsub(/Ρ/,"S")\
  .gsub(/ς/,"t")\
  .gsub(/Ò/,"T")\
  .gsub(/σ/,"u")\
  .gsub(/Σ/,"U")\
  .gsub(/τ/,"f")\
  .gsub(/Τ/,"F")\
  .gsub(/υ/,"h")\
  .gsub(/Υ/,"H")\
  .gsub(/φ/,"c")\
  .gsub(/Φ/,"C")\
  .gsub(/χ/,"ch")\
  .gsub(/Χ/,"Ch")\
  .gsub(/ψ/,"sh")\
  .gsub(/Ψ/,"Sh")\
  .gsub(/ω/,"sch")\
  .gsub(/Ω/,"Sch")\
  .gsub(/ϊ/,"")\
  .gsub(/Ϊ/,"")\
  .gsub(/ϋ/,"i")\
  .gsub(/Ϋ/,"I")\
  .gsub(/ό/,"")\
  .gsub(/ά/,"")\
  .gsub(/ύ/,"e")\
  .gsub(/έ/,"E")\
  .gsub(/ώ/,"ju")\
  .gsub(/ή/,"Ju")\
  .gsub(/ÿ/,"ja")\
  .gsub(/ί/,"Ja")\
  .gsub(/[ -]/,"_")\
  .gsub(/\W/,"")
end

def anti_trans(text)
  text\
  .gsub(/ch/i,"χ").gsub(/zh/i,"ζ").gsub(/sh/i,"ψ").gsub(/(ja|ya)/i,"ÿ").gsub(/(jo|yo)/i,"Έ").gsub(/(ju|yu)/i,"ώ")\
  .gsub(/a/i,"ΰ")\
  .gsub(/b/i,"α")\
  .gsub(/c/i,"φ")\
  .gsub(/d/i,"δ")\
  .gsub(/e/i,"ε")\
  .gsub(/f/i,"τ")\
  .gsub(/g/i,"γ")\
  .gsub(/h/i,"υ")\
  .gsub(/i/i,"θ")\
  .gsub(/j/i,"ζ")\
  .gsub(/k/i,"κ")\
  .gsub(/l/i,"λ")\
  .gsub(/m/i,"μ")\
  .gsub(/n/i,"ν")\
  .gsub(/o/i,"ξ")\
  .gsub(/p/i,"ο")\
  .gsub(/q/i,"κ")\
  .gsub(/r/i,"π")\
  .gsub(/s/i,"ρ")\
  .gsub(/t/i,"ς")\
  .gsub(/u/i,"σ")\
  .gsub(/v/i,"β")\
  .gsub(/w/i,"β")\
  .gsub(/x/i,"κρ")\
  .gsub(/y/i,"ι")\
  .gsub(/z/i,"η")\
  .gsub("_"," ")
end

def ru_capitalize(text)
  text[/[ΐ-ίΰ-ÿ]/] = text[/[ΐ-ίΰ-ÿ]/]\
  .sub("ΰ","ΐ")\
  .sub("α","Α")\
  .sub("β","Β")\
  .sub("γ","Γ")\
  .sub("δ","Δ")\
  .sub("ε","Ε")\
  .sub("Έ","¨")\
  .sub("ζ","Ζ")\
  .sub("η","Η")\
  .sub("θ","Θ")\
  .sub("ι","Ι")\
  .sub("κ","Κ")\
  .sub("λ","Λ")\
  .sub("μ","Μ")\
  .sub("ν","Ν")\
  .sub("ξ","Ξ")\
  .sub("ο","Ο")\
  .sub("π","Π")\
  .sub("ρ","Ρ")\
  .sub("ς","Ò")\
  .sub("σ","Σ")\
  .sub("τ","Τ")\
  .sub("υ","Υ")\
  .sub("φ","Φ")\
  .sub("χ","Χ")\
  .sub("ψ","Ψ")\
  .sub("ω","Ω")\
  .sub("ϊ","Ϊ")\
  .sub("ϋ","Ϋ")\
  .sub("ό","ά")\
  .sub("ύ","έ")\
  .sub("ώ","ή")\
  .sub("ÿ","ί")
  return text
end

Dir["*.*"].map do
  |elem|
  File.rename(elem, ru_capitalize(anti_trans(elem[0..-4]).gsub("  "," ").gsub(/ ([ΰ-ÿ])/){" "+ru_capitalize($1)})+File.extname(elem))
  elem
end